import { Helmet, HelmetProvider } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import Navbar from "@/components/Navbar";
import StudioFooter from "@/components/studio/StudioFooter";

export default function AboutBill() {
  return <HelmetProvider><Helmet><title>About Bill Bricker — VibeCo</title><meta name="description" content="Strategic partnerships, business development, and hands-on building. VibeCo is Bill Bricker's working AI lab." /></Helmet><div className="studio-site"><Navbar /><main id="main-content" className="studio-container studio-page-main">
    <header className="studio-about-intro"><div><p className="studio-eyebrow">Bill Bricker / the person behind VibeCo</p><h1>Commercial questions.<br /><span>Working answers.</span></h1></div><p className="studio-about-lede">I'm interested in the space between seeing an opportunity and making something useful happen.</p></header>
    <section className="studio-about-body" aria-label="Bill's approach"><div className="studio-about-note"><span className="studio-about-mark" aria-hidden="true">B.</span><p>Strategic Partnerships<br />& Business Development</p><a href="https://picklebill.github.io/Brick/" target="_blank" rel="noreferrer" className="studio-text-link">My experience & career story <ArrowUpRight size={17} /></a></div><div className="studio-about-prose"><h2>A place to see how I think.</h2><p>My work brings together strategic partnerships, business development, enterprise sales, and hands-on experimentation. I care about who a product is for, what makes it worth using, and how the people around it can make it work.</p><p>VibeCo is my working lab for those questions. It brings structure to a rough idea, makes room for competing perspectives, and turns the conversation into something you can act on.</p><p>You can use it to research an opportunity, explore a business idea, challenge an initiative, or work through a decision. The same tools I use are here for you to try.</p><h2>AI opens up the thinking.<br />Judgment still matters.</h2><p>A persuasive answer isn't automatically a good answer. That's why the workbench separates evidence from assumptions, surfaces uncertainty, and makes the next experiment as important as the recommendation.</p><p>The projects in this lab are explorations and prototypes. They're here to make an idea tangible, learn where it breaks, and find a better question.</p></div></section>
    <section className="studio-about-invitation"><p className="studio-eyebrow">If we're talking about working together</p><h2>Start with a question<br />that matters to you.</h2><p>Open a worked example, look at the tradeoffs, and ask what you'd change. That's a much more useful conversation than a list of tools.</p><div><Link className="studio-button" to="/examples">See how it works <ArrowRight size={17} /></Link><a className="studio-text-link" href="https://picklebill.github.io/Brick/" target="_blank" rel="noreferrer">Explore my experience <ArrowUpRight size={17} /></a></div></section>
  </main><StudioFooter /></div></HelmetProvider>;
}
