import { Helmet, HelmetProvider } from "react-helmet-async";
import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import Navbar from "@/components/Navbar";
import StudioFooter from "@/components/studio/StudioFooter";
import { studioProjects, studioStarters, workbenchUrl } from "@/data/studio";

export default function Examples() {
  return <HelmetProvider><Helmet><title>Examples & explorations — VibeCo</title><meta name="description" content="Open a worked example before you start, or explore Bill Bricker's catalog of product prototypes and website concepts." /></Helmet><div className="studio-site"><Navbar /><main id="main-content" className="studio-container studio-page-main">
    <header className="studio-page-intro"><p className="studio-eyebrow">Take a look inside</p><h1>Good questions.<br /><span>Useful places to start.</span></h1><p>See what comes out of the workbench before putting something in. These prepared examples open instantly and don't start an AI run.</p></header>
    <section aria-label="Worked examples" className="studio-examples-list">{studioStarters.map((starter, index) => <article key={starter.purpose} className="studio-example-row"><div className="studio-example-type"><span>0{index + 1}</span><p>{starter.label}</p></div><div className="studio-example-content"><h2>{starter.title}</h2><p>{starter.question}</p><div className="studio-example-outcome"><span>You leave with</span><p>{starter.outcome}</p></div><span className="studio-example-label">Prepared example · illustrative analysis</span></div><div className="studio-example-actions"><Link to={`/simulate?example=${starter.purpose}`} className="studio-button">Open example <ArrowUpRight size={16} /></Link><Link to={workbenchUrl(starter.purpose, starter.question)} className="studio-text-link">Use this starting question <ArrowRight size={15} /></Link></div></article>)}</section>
    <section id="catalog" className="studio-catalog" aria-labelledby="catalog-title"><div className="studio-section-heading"><div><p className="studio-eyebrow">The wider lab · 14 explorations</p><h2 id="catalog-title">Built to explore<br />what could be.</h2></div><p>Product prototypes and website concepts, each investigating a different problem. These demos show design intent; they don't establish customer adoption or production readiness.</p></div><div className="studio-catalog-list">{studioProjects.map((project, index) => <a className="studio-catalog-row" href={project.url} target="_blank" rel="noreferrer" key={project.name} aria-label={`Explore ${project.name}, ${project.maturity.toLowerCase()} (opens in a new tab)`}><span className="studio-catalog-number">{String(index + 1).padStart(2, "0")}</span><img src={project.thumbnail} alt="" loading="lazy" /><div className="studio-catalog-description"><span className="studio-catalog-category">{project.category}</span><h3>{project.name}</h3><p>{project.description}</p></div><span className="studio-maturity">{project.maturity}</span><ArrowUpRight size={21} className="studio-catalog-arrow" /></a>)}</div></section>
    <section className="studio-page-cta"><p className="studio-eyebrow">Your turn</p><h2>What's the question<br />you keep coming back to?</h2><Link to="/simulate" className="studio-button">Bring it to the workbench <ArrowRight size={17} /></Link></section>
  </main><StudioFooter /></div></HelmetProvider>;
}
